const book = require('./book.routes')
const bookings = require('./bookings.routes')
const user = require('./user.routes')
const airports = require('./airports.routes')
const locations = require('./locations.routes')
const price = require('./price.routes')
const search = require('./search.routes')
const book_flight = require('./book_flight.routes')
const payment_methods = require('./payment_methods.routes')
const login = require('./login.routes')
const sign_up = require('./sign_up.routes')
const stripewebhook = require('./stripewebhook.routes')
const payment = require('./payment.routes')
const seat_map = require('./seat_map.routes')
const logs = require('./logs.routes')
const athena = require('./athena.routes')
const create = require('./create.routes')
const get = require('./get.routes')
const athena_add = require('./athena_add.routes')
const schema = require('./schema.routes')

const selectionRoute = (app) => {
	app.use('/', book)
	app.use('/', bookings)
	app.use('/', user)
	app.use('/', airports)
	app.use('/', locations)
	app.use('/', price)
	app.use('/', search)
	app.use('/', book_flight)
	app.use('/', payment_methods)
	app.use('/', login)
	app.use('/', sign_up)
	app.use('/', stripewebhook)
	app.use('/', payment)
	app.use('/', seat_map)
	app.use('/', logs)
	app.use('/', athena)
	app.use('/', create)
	app.use('/', get)
	app.use('/', athena_add)
	app.use('/', schema)
}
module.exports = { selectionRoute }
